# This file is used by the GitHub Action Labeler
# https://github.com/actions/labeler

# Add 'bug' label to any changes within 'custom_components/tgtg' folder
bug:
- custom_components/tgtg/**/*

# Add 'enhancement' label to any changes within 'scripts' folder
enhancement:
- scripts/**/*

# Add 'documentation' label to any changes within 'README.md' file
documentation:
- README.md
